/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calc.h"

bool_t
xdr_data (XDR *xdrs, data *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->op0))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->op1))
		 return FALSE;
	return TRUE;
}
