/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"

void
prog_add_1(char *host) {
    CLIENT *clnt;
    double *result_1;
    data do_addn_1_arg;

#ifndef DEBUG
    clnt = clnt_create(host, PROG_ADD, VERS_ADD, "udp");
    if (clnt == NULL) {
        clnt_pcreateerror(host);
        exit(1);
    }
#endif /* DEBUG */

    printf("\nEnter operands: ");
    int times = 0;
    while (times < 2) {
        switch (times) {
            case 0:
                scanf("%lf", &do_addn_1_arg.op0);
                times++;
                break;
            case 1:
                scanf("%lf", &do_addn_1_arg.op1);
                times++;
                break;
            default:
                break;
        }
    }

    result_1 = do_addn_1(&do_addn_1_arg, clnt);
    if (result_1 == (double *) NULL) {
        clnt_perror(clnt, "call failed");
    }

    printf("\nSum is:  %.2f\n", *result_1);
    puts("\t----------");
    puts("++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++");

#ifndef DEBUG
    clnt_destroy(clnt);
#endif  /* DEBUG */
}

void
prog_sub_1(char *host) {
    CLIENT *clnt;
    double *result_1;
    data do_subn_1_arg;

#ifndef DEBUG
    clnt = clnt_create(host, PROG_SUB, VERS_SUB, "udp");
    if (clnt == NULL) {
        clnt_pcreateerror(host);
        exit(1);
    }
#endif /* DEBUG */

    printf("\nEnter operands: ");
    int times = 0;
    while (times < 2) {
        switch (times) {
            case 0:
                scanf("%lf", &do_subn_1_arg.op0);
                times++;
                break;
            case 1:
                scanf("%lf", &do_subn_1_arg.op1);
                times++;
                break;
            default:
                break;
        }
    }

    result_1 = do_subn_1(&do_subn_1_arg, clnt);
    if (result_1 == (double *) NULL) {
        clnt_perror(clnt, "call failed");
    }

    printf("\nDifference is:  %.2f\n", *result_1);
    puts("\t\t----------");
    puts("------------------------------------------------------------");

#ifndef DEBUG
    clnt_destroy(clnt);
#endif  /* DEBUG */
}

void
prog_div_1(char *host) {
    CLIENT *clnt;
    double *result_1;
    data do_divn_1_arg;

#ifndef DEBUG
    clnt = clnt_create(host, PROG_DIV, VERS_DIV, "udp");
    if (clnt == NULL) {
        clnt_pcreateerror(host);
        exit(1);
    }
#endif /* DEBUG */

    printf("\nEnter operands: ");
    int times = 0;
    while (times < 2) {
        switch (times) {
            case 0:
                scanf("%lf", &do_divn_1_arg.op0);
                times++;
                break;
            case 1:
                scanf("%lf", &do_divn_1_arg.op1);
                times++;
                break;
            default:
                break;
        }
    }

    result_1 = do_divn_1(&do_divn_1_arg, clnt);
    if (result_1 == (double *) NULL) {
        clnt_perror(clnt, "call failed");
    }

    printf("\nQuotient is:  %.2f\n", *result_1);
    puts("\t\t----------");
    puts("////////////////////////////////////////////////////////////");

#ifndef DEBUG
    clnt_destroy(clnt);
#endif  /* DEBUG */
}

void
prog_mul_1(char *host) {
    CLIENT *clnt;
    double *result_1;
    data do_muln_1_arg;

#ifndef DEBUG
    clnt = clnt_create(host, PROG_MUL, VERS_MUL, "udp");
    if (clnt == NULL) {
        clnt_pcreateerror(host);
        exit(1);
    }
#endif /* DEBUG */

    printf("\nEnter operands: ");
    int times = 0;
    while (times < 2) {
        switch (times) {
            case 0:
                scanf("%lf", &do_muln_1_arg.op0);
                times++;
                break;
            case 1:
                scanf("%lf", &do_muln_1_arg.op1);
                times++;
                break;
            default:
                break;
        }
    }

    result_1 = do_muln_1(&do_muln_1_arg, clnt);
    if (result_1 == (double *) NULL) {
        clnt_perror(clnt, "call failed");
    }

    printf("\nProduct is:  %.2f\n", *result_1);
    puts("\t\t----------");
    puts("************************************************************");

#ifndef DEBUG
    clnt_destroy(clnt);
#endif  /* DEBUG */
}

int
main(int argc, char *argv[]) {
    char *host;

    if (argc < 2)
        host = "localhost";
    else
        host = argv[1];

    int op;
    puts("\nWelcome to calc superior");
    while (1) {
        printf("\n Specify operation:\n\n"
                "  1. Addition\t\t(+)\n"
                "  2. Subtraction\t(-)\n"
                "  3. Division\t\t(/)\n"
                "  4. Multiplication\t(*)\n"
                "  5. Exit\n \t>> ");
        scanf("%d", &op);

        switch (op) {
            case 1:
                prog_add_1(host);
                break;
            case 2:
                prog_sub_1(host);
                break;
            case 3:
                prog_div_1(host);
                break;
            case 4:
                prog_mul_1(host);
                break;
            case 5:
                puts("\nSee you again!\n");
                exit(0);
                break;
            default:
                break;
        }
    }

    exit(0);
}
